# Basic Information 
title: Zhaochen Yu
position: MSE. Student
affiliation: Nanyang Technological University
affiliation_link: https://ntu.edu.sg/
affiliation_logo: ./assets/img/NTU_coat_of_arms.png
email: bityzcedu (at) 163.com

# Search Engine Optimization (SEO)
# The following information is used to improve the website traffic from search engines, e.g., Google.
keywords: trafalgar zhaochen yu, zhaochen yu, yu zhaochen 
description: Zhaochen Yu is a MSE student, Nanyang Technological University.
canonical: https://zhaochenyu0201.github.io/

# Links 
# If you don't need one of them, you may delete the corresponding line.
google_scholar: https://scholar.google.com/citations?user=9RNgZOIAAAAJ&hl=en
# cv_link: assets/files/curriculum_vitae.pdf
github_link: https://github.com/zhaochenyu0201
linkedin: https://www.linkedin.com/in/zhaochen-yu-5a354b326/
twitter: https://x.com/yu_trafalgar

# Images (e.g., your profile picture and your website's favicon) 
# "favicon" and "favicon_dark" are used for the light and dark modes, respectively. 
avatar: ./assets/img/yzc.jpg
favicon: ./assets/img/NTU_coat_of_arms.png
favicon_dark: ./assets/img/NTU_coat_of_arms.png

# Footnote
# You may use the option to disable the footnote, "Powered by Jekyll and Minimal Light theme."
enable_footnote: true

# Auto Dark Mode
# You may use the option to disable the automatic dark theme
auto_dark_mode: true

# Font
# You can use this option to choose between Serif or Sans Serif fonts.
font: "Serif" # or "Sans Serif"

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
  - html_source_file/
